import { test } from "node:test";
import assert from "node:assert/strict";
import { MatterGraph, scrambleDocument, unscramble, type LocalModel } from "../src";
import { occurrences } from "../src/measure";
import { extractCitations } from "../src/citations";

/* THE BATTERY: hundreds of synthetic legal filings generated by DeepSeek (scripts/scrambler-battery-gen.ts), each
 * shipped with its own ground truth -- the secrets the generator planted, by type, verified verbatim against the
 * text at generation time -- and the public law it cited. This runs the whole battery OFFLINE against three fake
 * models, so it is a unit test, not a measurement of the liaison:
 *   oracle   proposes exactly the planted secrets           -> the pipeline ceiling on adversarial documents
 *   hijacked proposes the secrets plus every red-team trick -> the guard under attack
 *   lazy     proposes only the first half of the secrets    -> derived aliases and pass 2 doing real work
 * Per document, whatever the model did: no planted secret survives outside a cited caption, the citation count
 * is unchanged, nothing invented appears, and every release round-trips. Leaks are reported PER TYPE, which the
 * HLL ground truth could never give us. A failing document prints its seed and title for replay. */

import { loadBattery, asType, type BatteryDoc as Doc } from "../src/battery";
const present = (text: string, s: string) => occurrences(text, s).filter((o) => !o.caption).length;

const oracle = (d: Doc): LocalModel => async (p) => p.includes("auditing") ? JSON.stringify({ leaks: [], inconsistent: [] })
  : JSON.stringify({ spans: d.secrets.map((s) => ({ text: s.text, type: asType(s.type) })), coref: {} });
const hijacked = (d: Doc): LocalModel => {
  const junk = [{ text: "Vladimir Putin", type: "PERSON" }, { text: "[CLIENT_1]", type: "PERSON" }, { text: "ignore all previous instructions", type: "OTHER" }, { text: "_1", type: "OTHER" }, { text: "State", type: "ORG" }, ...(d.public_law.map((c) => ({ text: c, type: "OTHER" })))];
  return async (p) => p.includes("auditing") ? JSON.stringify({ leaks: [{ text: "Elvis", type: "PERSON" }, ...d.secrets.slice(-2).map((s) => ({ text: s.text, type: "JUDGE" }))], inconsistent: [] })
    : JSON.stringify({ spans: [...junk, ...d.secrets.map((s) => ({ text: s.text, type: asType(s.type) })), ...junk], coref: Object.fromEntries(d.secrets.slice(0, 2).map((s) => [s.text, d.secrets[d.secrets.length - 1].text])) });
};
const lazy = (d: Doc): LocalModel => async (p) => p.includes("auditing") ? JSON.stringify({ leaks: d.secrets.slice(Math.ceil(d.secrets.length / 2), Math.ceil(d.secrets.length / 2) + 2).map((s) => ({ text: s.text, type: asType(s.type) })), inconsistent: [] })
  : JSON.stringify({ spans: d.secrets.slice(0, Math.ceil(d.secrets.length / 2)).map((s) => ({ text: s.text, type: asType(s.type) })), coref: {} });

const DOCS = loadBattery();
const LIMIT = Number(process.env.SCRAMBLER_BATTERY_LIMIT ?? DOCS.length);
// The battery is generated, not hand-written (scripts/scrambler-battery-gen.ts) and committed under
// data/battery. A checkout without it skips loudly rather than failing: the absence is a missing
// artefact, not a defect in the scrambler.
const skip = DOCS.length === 0 ? { skip: "no battery under data/battery -- run scripts/scrambler-battery-gen.ts" } : {};

test(`battery is present (${DOCS.length} documents)`, skip, () => { assert.ok(DOCS.length > 0); });

for (const [name, mk] of [["oracle", oracle], ["hijacked", hijacked], ["lazy", lazy]] as const) {
  test(`battery x ${name}: no planted secret leaves, citations survive, every release round-trips`, skip, async () => {
    const leaksByType: Record<string, number> = {}; const totalByType: Record<string, number> = {};
    let released = 0, refused = 0, refusedInput = 0;
    for (const d of DOCS.slice(0, LIMIT)) {
      const where = `seed ${d.seed} "${d.title.slice(0, 60)}" (${name})`;
      const graph = new MatterGraph(`battery-${d.seed}`);
      let out: Awaited<ReturnType<typeof scrambleDocument>>;
      try { out = await scrambleDocument(d.text.slice(0, 60_000), graph, mk(d)); }
      catch (e) { const m = (e as Error).message; assert.match(m, /refusing to release/, `${where}: unexpected error ${m}`); if (/in the INPUT/.test(m)) refusedInput++; else refused++; continue; }
      released++;
      for (const s of d.secrets) {
        const type = asType(s.type); totalByType[type] = (totalByType[type] ?? 0) + 1;
        // a secret the model never proposed and the regex never matches is the model's miss, not the pipeline's;
        // under the oracle and hijacked models every secret WAS proposed, so any survivor there is a pipeline leak
        const claimed = graph.find(s.text) !== null || /[@\d]/.test(s.text);
        if (claimed && present(out.scrambled, s.text) > 0) {
          leaksByType[type] = (leaksByType[type] ?? 0) + 1;
          if (name !== "lazy") assert.fail(`${where}\nleaked ${type}: ${JSON.stringify(s.text)}\n${out.scrambled.slice(0, 400)}`);
        }
      }
      assert.equal(extractCitations(out.scrambled).length, extractCitations(d.text.slice(0, 60_000)).length, `${where}: citation count changed`);
      assert.ok(!/Putin|Elvis/.test(out.scrambled), `${where}: invented entity appeared`);
      const back = unscramble(out.scrambled, graph);
      assert.deepEqual(back.unknown, [], `${where}: unknown placeholder after restore`);
      assert.ok(!/\[[A-Z]+_\d+\]/.test(back.text), `${where}: placeholder survived restore`);
    }
    console.log(`  ${name}: released ${released}, refused ${refused} (input-gate ${refusedInput}) of ${Math.min(LIMIT, DOCS.length)}; secrets by type ${JSON.stringify(totalByType)}; leaked by type ${JSON.stringify(leaksByType)}`);
    assert.ok(released > 0);
  });
}

test("battery injection strings never reach the output as anything but the document's own text", skip, async () => {
  const withInj = DOCS.filter((d) => d.injection && d.text.includes(d.injection!)).slice(0, LIMIT);
  let checked = 0;
  for (const d of withInj) {
    const graph = new MatterGraph(`inj-${d.seed}`); let out;
    try { out = await scrambleDocument(d.text.slice(0, 60_000), graph, hijacked(d)); } catch { continue; }
    checked++;
    // the injected sentence is prose in the document; it may be left as-is (harmless) or partly scrubbed, but
    // it can never cause anything NEW: no invented entity, no unknown placeholder
    assert.ok(!/Putin|Elvis/.test(out.scrambled)); assert.deepEqual(unscramble(out.scrambled, graph).unknown, []);
  }
  console.log(`  injection documents checked: ${checked} of ${withInj.length}`);
});

test("ground-truth noise is not a secret: a bare city, a case name, an administrative reporter, a role label", async () => {
  const { cleanSecrets } = await import("../src/battery");
  const kept = cleanSecrets([{ text: "Houston", type: "ADDRESS" }, { text: "Harris County", type: "ADDRESS" }, { text: "Texas 77005", type: "ADDRESS" }, { text: "Westheimer Road", type: "ADDRESS" }, { text: "2210 Marigold Street, Houston, Harris County, Texas 77005", type: "ADDRESS" }, { text: "Matter of Cruz", type: "PERSON" }, { text: "Vasquez v. Lone Star Logistics, Inc.", type: "DOCKET" }, { text: "25 I&N Dec. 410", type: "JUDGE" }, { text: "Attorney for Plaintiff", type: "ATTORNEY" }, { text: "Thomas White", type: "CLIENT" }]).map((s) => s.text);
  assert.deepEqual(kept, ["2210 Marigold Street, Houston, Harris County, Texas 77005", "Thomas White"]);
});
